/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Protheus_main */

#ifndef _Included_com_Protheus_main
#define _Included_com_Protheus_main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Protheus_main
 * Method:    initializationRC4
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_Protheus_main_initializationRC4
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_Protheus_main
 * Method:    freeRC4Source
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Protheus_main_freeRC4Source
  (JNIEnv *, jclass);

/*
 * Class:     com_Protheus_main
 * Method:    getOutputStreamPointer
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_com_Protheus_main_getOutputStreamPointer
  (JNIEnv *, jclass);

/*
 * Class:     com_Protheus_main
 * Method:    RC4_Encrypt
 * Signature: ([CS[CS)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_Protheus_main_RC4_1Encrypt
  (JNIEnv *, jclass, jcharArray, jshort, jcharArray, jshort);

#ifdef __cplusplus
}
#endif
#endif
